const nullableNumber = { type: ["number", "null"] } as const;
const nullableString = { type: ["string", "null"] } as const;
const stringArray = { items: { type: "string" }, type: "array" } as const;

const report = {
  additionalProperties: false,
  properties: {
    code: { type: "string" },
    title: { type: "string" },
  },
  required: ["code", "title"],
  type: "object",
} as const;

const fight = {
  additionalProperties: true,
  properties: {
    averageItemLevel: nullableNumber,
    difficulty: nullableNumber,
    durationMs: { type: "number" },
    encounterID: { type: "number" },
    endTime: { type: "number" },
    id: { type: "number" },
    kill: { type: ["boolean", "null"] },
    name: { type: "string" },
    size: nullableNumber,
    startTime: { type: "number" },
    url: { type: "string" },
  },
  required: [
    "averageItemLevel",
    "difficulty",
    "durationMs",
    "encounterID",
    "endTime",
    "id",
    "kill",
    "name",
    "size",
    "startTime",
    "url",
  ],
  type: "object",
} as const;

const player = {
  additionalProperties: true,
  properties: {
    actorID: { type: "number" },
    className: nullableString,
    gameID: nullableNumber,
    itemLevel: nullableNumber,
    name: nullableString,
    server: nullableString,
    specName: nullableString,
  },
  required: [
    "actorID",
    "className",
    "gameID",
    "itemLevel",
    "name",
    "server",
    "specName",
  ],
  type: "object",
} as const;

const composition = {
  additionalProperties: false,
  properties: {
    classes: {
      additionalProperties: { type: "number" },
      type: "object",
    },
    playerCount: { type: "number" },
    specs: {
      additionalProperties: { type: "number" },
      type: "object",
    },
  },
  required: ["classes", "playerCount", "specs"],
  type: "object",
} as const;

const section = {
  additionalProperties: false,
  properties: {
    rows: {
      items: { additionalProperties: true, type: "object" },
      type: "array",
    },
    totalRows: { type: "number" },
    truncated: { type: "boolean" },
  },
  required: ["rows", "totalRows", "truncated"],
  type: "object",
} as const;

const damageMetrics = {
  absorbed: { type: "number" },
  effectiveDamage: { type: "number" },
  hits: { type: "number" },
  mitigated: { type: "number" },
  rawDamage: { type: "number" },
  unmitigatedDamage: { type: "number" },
} as const;

export const TOOL_OUTPUT_SCHEMAS: Record<
  string,
  Record<string, unknown>
> = {
  wcl_get_rate_limit: {
    additionalProperties: false,
    properties: {
      authMode: { enum: ["client", "user"], type: "string" },
      limitPerHour: { type: "number" },
      pointsResetIn: { type: "number" },
      pointsSpentThisHour: { type: "number" },
    },
    required: [
      "authMode",
      "limitPerHour",
      "pointsResetIn",
      "pointsSpentThisHour",
    ],
    type: "object",
  },
  wcl_get_fights: {
    additionalProperties: false,
    properties: {
      fights: {
        items: {
          additionalProperties: false,
          properties: {
            bossPercentage: nullableNumber,
            difficulty: nullableNumber,
            encounterID: { type: "number" },
            endTime: { type: "number" },
            fightPercentage: nullableNumber,
            id: { type: "number" },
            kill: { type: ["boolean", "null"] },
            lastPhase: nullableNumber,
            lastPhaseAsAbsoluteIndex: nullableNumber,
            lastPhaseIsIntermission: { type: ["boolean", "null"] },
            name: { type: "string" },
            phaseTransitions: {
              type: ["array", "null"],
              items: {
                additionalProperties: false,
                properties: {
                  fightRelativeStartTime: { type: "number" },
                  id: { type: "number" },
                  reportRelativeStartTime: { type: "number" },
                  startTime: { type: "number" },
                },
                required: [
                  "fightRelativeStartTime",
                  "id",
                  "reportRelativeStartTime",
                  "startTime",
                ],
                type: "object",
              },
            },
            size: nullableNumber,
            startTime: { type: "number" },
          },
          required: [
            "bossPercentage",
            "difficulty",
            "encounterID",
            "endTime",
            "fightPercentage",
            "id",
            "kill",
            "lastPhase",
            "lastPhaseAsAbsoluteIndex",
            "lastPhaseIsIntermission",
            "name",
            "phaseTransitions",
            "size",
            "startTime",
          ],
          type: "object",
        },
        type: "array",
      },
      freshness: {
        additionalProperties: false,
        properties: {
          ageMs: { type: "number" },
          fetchedAtEpochMs: { type: "number" },
        },
        required: ["ageMs", "fetchedAtEpochMs"],
        type: "object",
      },
      report: {
        additionalProperties: false,
        properties: {
          code: { type: "string" },
          endTime: { type: "number" },
          startTime: { type: "number" },
          title: { type: "string" },
        },
        required: ["code", "endTime", "startTime", "title"],
        type: "object",
      },
    },
    required: ["fights", "freshness", "report"],
    type: "object",
  },
  wcl_analyze_fight_set: {
    additionalProperties: false,
    properties: {
      caveats: stringArray,
      filters: {
        additionalProperties: false,
        properties: {
          abilityID: nullableNumber,
          sourceID: nullableNumber,
          targetID: nullableNumber,
        },
        required: ["abilityID", "sourceID", "targetID"],
        type: "object",
      },
      payloadStability: { type: "string" },
      report,
      scope: {
        additionalProperties: false,
        properties: {
          fightCount: { type: "number" },
          fightIDs: { items: { type: "number" }, type: "array" },
          fights: {
            items: { additionalProperties: true, type: "object" },
            type: "array",
          },
          totalDurationMs: { type: "number" },
        },
        required: ["fightCount", "fightIDs", "fights", "totalDurationMs"],
        type: "object",
      },
      sections: {
        items: {
          additionalProperties: false,
          properties: {
            dataType: { type: "string" },
            rows: {
              items: { additionalProperties: true, type: "object" },
              type: "array",
            },
            totalRows: { type: "number" },
            truncated: { type: "boolean" },
            view: { type: "string" },
          },
          required: ["dataType", "rows", "totalRows", "truncated", "view"],
          type: "object",
        },
        type: "array",
      },
    },
    required: [
      "caveats",
      "filters",
      "payloadStability",
      "report",
      "scope",
      "sections",
    ],
    type: "object",
  },
  wcl_get_player_info: {
    additionalProperties: false,
    properties: {
      actors: {
        items: {
          additionalProperties: false,
          properties: {
            gameID: nullableNumber,
            id: { type: "number" },
            name: { type: "string" },
            role: {
              enum: ["dps", "healers", "tanks", null],
              type: ["string", "null"],
            },
            server: nullableString,
            spec: nullableString,
            subType: { type: "string" },
            type: { type: "string" },
          },
          required: [
            "gameID",
            "id",
            "name",
            "role",
            "server",
            "spec",
            "subType",
            "type",
          ],
          type: "object",
        },
        type: "array",
      },
      logOwner: nullableString,
    },
    required: ["actors", "logOwner"],
    type: "object",
  },
  wcl_get_table: {
    additionalProperties: false,
    properties: {
      endTime: { type: "number" },
      fightDuration: { type: "number" },
      fightID: { type: "number" },
      reportCode: { type: "string" },
      startTime: { type: "number" },
      table: {},
      view: { type: "string" },
    },
    required: [
      "endTime",
      "fightDuration",
      "fightID",
      "reportCode",
      "startTime",
      "table",
      "view",
    ],
    type: "object",
  },
  wcl_get_events: {
    additionalProperties: false,
    properties: {
      dataType: { type: "string" },
      endTime: { type: "number" },
      events: { items: {}, type: "array" },
      fightDuration: { type: "number" },
      fightEndTime: { type: "number" },
      fightID: { type: "number" },
      fightStartTime: { type: "number" },
      nextPageTimestamp: { type: "number" },
      pagesReturned: { type: "number" },
      reportCode: { type: "string" },
      startTime: { type: "number" },
      truncated: { type: "boolean" },
    },
    required: [
      "dataType",
      "endTime",
      "events",
      "fightDuration",
      "fightEndTime",
      "fightID",
      "fightStartTime",
      "pagesReturned",
      "reportCode",
      "startTime",
      "truncated",
    ],
    type: "object",
  },
  wcl_find_peer_parses: {
    additionalProperties: true,
    properties: {
      candidatesScanned: { type: "number" },
      caveats: stringArray,
      durationTolerancePercent: { type: "number" },
      encounterID: { type: "number" },
      encounterName: nullableString,
      pagesRead: { type: "number" },
      peers: {
        items: {
          additionalProperties: false,
          properties: {
            amount: nullableNumber,
            bracketData: nullableNumber,
            className: nullableString,
            durationDeltaMs: { type: "number" },
            durationDeltaPercent: { type: "number" },
            durationMs: { type: "number" },
            fightID: { type: "number" },
            playerName: nullableString,
            reportCode: { type: "string" },
            specName: nullableString,
          },
          required: [
            "amount",
            "bracketData",
            "className",
            "durationDeltaMs",
            "durationDeltaPercent",
            "durationMs",
            "fightID",
            "playerName",
            "reportCode",
            "specName",
          ],
          type: "object",
        },
        type: "array",
      },
      rankingResultsTruncated: { type: "boolean" },
      rejectedEntries: { type: "number" },
      targetDurationMs: { type: "number" },
    },
    required: [
      "candidatesScanned",
      "caveats",
      "durationTolerancePercent",
      "encounterID",
      "encounterName",
      "pagesRead",
      "peers",
      "rankingResultsTruncated",
      "rejectedEntries",
      "targetDurationMs",
    ],
    type: "object",
  },
  wcl_get_fight_context: {
    additionalProperties: false,
    properties: {
      combatantInfoIncluded: { type: "boolean" },
      composition,
      fight,
      players: { items: player, type: "array" },
      report,
    },
    required: [
      "combatantInfoIncluded",
      "composition",
      "fight",
      "players",
      "report",
    ],
    type: "object",
  },
  wcl_get_player_fight_summary: {
    additionalProperties: true,
    properties: {
      fightDurationMs: { type: "number" },
      fightID: { type: "number" },
      metrics: {
        additionalProperties: true,
        properties: {
          aliveTimeMs: { type: "number" },
          bossDamage: { type: "number" },
          buffs: { items: { type: "object" }, type: "array" },
          casts: { items: { type: "object" }, type: "array" },
          durationMs: { type: "number" },
          totalDamage: { type: "number" },
        },
        required: [
          "aliveTimeMs",
          "bossDamage",
          "buffs",
          "casts",
          "durationMs",
          "totalDamage",
        ],
        type: "object",
      },
      parsePercentiles: { type: "object" },
      payloadStability: { type: "string" },
      rankingsIncluded: { type: "boolean" },
      rawTables: { type: "object" },
      rawTablesIncluded: { type: "boolean" },
      reportCode: { type: "string" },
      sourceID: { type: "number" },
    },
    required: [
      "fightDurationMs",
      "fightID",
      "metrics",
      "parsePercentiles",
      "payloadStability",
      "rankingsIncluded",
      "rawTablesIncluded",
      "reportCode",
      "sourceID",
    ],
    type: "object",
  },
  wcl_get_fight_overview: {
    additionalProperties: false,
    properties: {
      caveats: stringArray,
      composition,
      fight,
      payloadStability: { type: "string" },
      players: { items: player, type: "array" },
      report,
      sections: {
        additionalProperties: false,
        properties: {
          damageDone: section,
          damageTaken: section,
          deaths: section,
          dispels: section,
          healing: section,
          interrupts: section,
        },
        required: [
          "damageDone",
          "damageTaken",
          "deaths",
          "dispels",
          "healing",
          "interrupts",
        ],
        type: "object",
      },
    },
    required: [
      "caveats",
      "composition",
      "fight",
      "payloadStability",
      "players",
      "report",
      "sections",
    ],
    type: "object",
  },
  wcl_get_fight_window_context: {
    additionalProperties: false,
    properties: {
      caveats: stringArray,
      channels: {
        items: {
          additionalProperties: false,
          properties: {
            dataType: { type: "string" },
            fetchedEvents: { type: "number" },
            nextStartTime: { type: "number" },
            returnedEvents: { type: "number" },
            upstreamTruncated: { type: "boolean" },
          },
          required: [
            "dataType",
            "fetchedEvents",
            "returnedEvents",
            "upstreamTruncated",
          ],
          type: "object",
        },
        type: "array",
      },
      fight: {
        additionalProperties: false,
        properties: {
          durationMs: { type: "number" },
          id: { type: "number" },
          url: { type: "string" },
        },
        required: ["durationMs", "id", "url"],
        type: "object",
      },
      focusAbilityName: nullableString,
      payloadStability: { type: "string" },
      report,
      timeline: {
        items: {
          additionalProperties: true,
          properties: { channel: { type: "string" } },
          required: ["channel"],
          type: "object",
        },
        type: "array",
      },
      window: {
        additionalProperties: false,
        properties: {
          coordinate: { type: "string" },
          durationMs: { type: "number" },
          endTime: { type: "number" },
          startTime: { type: "number" },
        },
        required: ["coordinate", "durationMs", "endTime", "startTime"],
        type: "object",
      },
    },
    required: [
      "caveats",
      "channels",
      "fight",
      "focusAbilityName",
      "payloadStability",
      "report",
      "timeline",
      "window",
    ],
    type: "object",
  },
  wcl_rank_damage_taken_by_ability: {
    additionalProperties: true,
    properties: {
      abilityRankings: { items: { type: "object" }, type: "array" },
      caveats: stringArray,
      evidenceCompleteness: { type: "string" },
      fight,
      match: { type: "object" },
      matchedPlayers: { type: "number" },
      metricDefinitions: { type: "object" },
      percentageDenominator: nullableString,
      players: {
        items: {
          additionalProperties: true,
          properties: {
            actorID: { type: "number" },
            hitSharePercent: nullableNumber,
            name: { type: "string" },
            type: nullableString,
            ...damageMetrics,
          },
          required: [
            "absorbed",
            "actorID",
            "effectiveDamage",
            "hits",
            "hitSharePercent",
            "mitigated",
            "name",
            "rawDamage",
            "type",
            "unmitigatedDamage",
          ],
          type: "object",
        },
        type: "array",
      },
      report,
      scope: {
        additionalProperties: false,
        properties: {
          fightCount: { type: "number" },
          fightIDs: { items: { type: "number" }, type: "array" },
          fights: {
            items: { additionalProperties: true, type: "object" },
            type: "array",
          },
        },
        required: ["fightCount", "fightIDs", "fights"],
        type: "object",
      },
      totalHits: nullableNumber,
    },
    required: [
      "abilityRankings",
      "caveats",
      "evidenceCompleteness",
      "match",
      "matchedPlayers",
      "metricDefinitions",
      "percentageDenominator",
      "players",
      "report",
      "scope",
      "totalHits",
    ],
    type: "object",
  },
  wcl_graphql: {
    additionalProperties: true,
    properties: {
      data: {},
      errors: {
        items: {
          additionalProperties: true,
          properties: { message: { type: "string" } },
          required: ["message"],
          type: "object",
        },
        type: "array",
      },
    },
    type: "object",
  },
};
